version: '3'

services:
  master:
    image: postgres:10
    # ports:
      # - ${MASTER_PORT}:5432
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./master.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PASSWORD}
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
  replica:
    image: postgres:10
    # ports:
      # - ${REPLICA_PORT}:5432
    volumes:
      - ./init_replica.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./replica.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PASSWORD}
